name: Deploy

on:
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.1.15f1
  PROJECT_PATH: Test

jobs:
  checklicense:
    name: Check for Unity License
    runs-on: ubuntu-latest
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps: 
      - name: Check whether Unity Activation requests should be done
        id: checklicense_job
        run: |
          echo "Skip activation job: ${{ env.UNITY_LICENSE != '' }}"
          echo "::set-output name=is_unity_license_set::${{ env.UNITY_LICENSE != '' }}"

  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    needs: [checklicense]
    if: needs.checklicense.outputs.is_unity_license_set == 'true'
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ${{ env.PROJECT_PATH }}
        unityVersion:
          - ${{ env.UNITY_VERSION }}
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      # Checkout project
      - name: Checkout Project
        uses: actions/checkout@v2.3.4
        with:
          lfs: true
          
      # Cache
      - name: Cache files 
        uses: actions/cache@v2.1.4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      
      # Build
      - name: Build
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          buildName: Example Project
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      
      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Build
          path: build
