name: Integrate
 
on:
  pull_request:
    branches: [ main ]

env:
 UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 UNITY_VERSION: ${{ 2020.1.15f1 }}
 PROJECT_PATH: Test

jobs:
  testsAllModes:
    name: Run EditMode and PlayMode Tests ✨
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      
      # Cache Library Files
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
         path: ${{ env.projectPath }}/Library
         key: Library-${{ env.projectPath }}
         restore-keys: |
          Library-
      
      # Run Tests
      - name: Run All Tests
        uses: game-ci/unity-test-runner@v2.0-alpha-3
        id: tests
        with:
         unityVersion: ${{ env.UNITY_VERSION }}
         projectPath: ${{ env.projectPath }}
         testMode: all
         customParameters: "-nographics"
      
      # Upload Results
      - name: Upload Results
        uses: actions/upload-artifact@v2.2.2
        if: always()
        with:
         name: Test Results (All)
         path: ${{ steps.tests.outputs.artifactsPath }}
