name: Integrate
 
on:
  pull_request:
    branches: [ main ]

jobs:
  testsAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
     matrix:
      projectPath:
       - Test
      testMode:
       - playmode
       - editmode
    steps:
      # Checkout code
      - uses: actions/checkout@v2
      
      # Cache Library Files
      - uses: action/cache@v2
        with:
         path: ${{ matrix.projectPath }}/Library
         key: Library-${{ matrix.projectPath }}
         restore-keys: |
          Library-
      
      # Run Tests
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
         projectPath: ${{ matrix.projectPath }}
         testMode: ${{ matrix.testMode }}
         artifactsPath: ${{ matrix.testMode }}-artifacts
         githubToken: ${{ secrets.GITHUB_TOKEN }}
         checkName: ${{ matrix.testMode }} Test Results
      
      # Upload Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
         name: Test Results for ${{ matrix.testMode }}
         path: ${{ steps.tests.outputs.artifactsPath }}
