name: Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
