name: Validate Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
    - name: Lint Commits    
      uses: actions-ecosystem/action-lint-commits@v1
      id: lint-commits
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        regex: '^\w+(.+): .+' # e.g. "feat(api): Add /users/get" or "ci: Adds CI workflow"
        format: markdown

    - name: Post warning comment
      uses: actions-ecosystem/action-create-comment@v1
      if: ${{ steps.lint-commits.outputs.unmatched_commits != '' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          The following commits needs their message changes:
          ${{ steps.lint-commits.outputs.unmatched_commits }}
          The format `<type>(<scope>): <subject>` or `<type>: <subject>` is acceptable. e.g., `feat(api): Add /users/get` or `ci: Adds CI workflow`

    - name: Fail when commits don't pass lint
      if: ${{ steps.lint-commits.outputs.unmatched_commits != '' }}
      run: exit 1

  bump-version:
    name: Bump Semver
    runs-on: ubuntu-latest
    needs: [lint-commits]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check for Release Label in PR
        uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ startsWith(github.event.label.name, 'release/') }}
      
      - name: Fail when no label is found
        if: ${{ steps.release-label.outputs.level == null }}
        run: exit 1

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true

      - name: Bump Semver
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - name: Create Comment about Bumped Semver
        uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This PR will update [${{ github.repository }}](https://github.com/${{ github.repository }}) from [${{ steps.get-latest-tag.outputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.get-latest-tag.outputs.tag }}) to ${{ steps.bump-semver.outputs.new_version }} :rocket:
            If this update isn't as you expected, you may want to change or remove the *release label*.
